import Vue from 'vue';
import ResearchParagraphComponent from './ResearchParagraphComponent';
import ResearchImageComponent from './ResearchImageComponent';
import ResearchTableComponent from './ResearchTableComponent';
import ResearchElement from './ResearchElement';
import buttonWithEdit from './buttonWithEdit';
import referenceButton from './referenceButton';
import CitationsComponent from './CitationsComponent';
import uploadImageComponent from './uploadImageComponent';
import ResearchSubtitleModal from './ResearchSubtitleModal';
import InsertTableComponent from './InsertTableComponent';
import ResearchCard from './ResearchCard';
import ResearchSnackbar from './ResearchSnackbar';
import ResearchChapterCard from './ResearchChapterCard';
import ResearchOneElement from './ResearchOneElement';
import ResearchModal from './ResearchModal';
import ThesisProjectGeneratorButton from './ThesisProjectGeneratorButton';
import ResearchHover from './ResearchHover';
import easyResearchOverlay from './easyResearchOverlay';
import expResearchElement from './expResearchElement';
import researchElementCard from './researchElementCard';
import researchElementSelector from './1ResearchElementSelector';
import richTextarea from './richTextarea';
import Highlightable from './Highlightable';
Vue.component('ResearchParagraphComponent', ResearchParagraphComponent);
Vue.component('ResearchElement', ResearchElement);
Vue.component('buttonWithEdit', buttonWithEdit);
Vue.component('referenceButton', referenceButton);
Vue.component('CitationsComponent', CitationsComponent);
Vue.component('ResearchImageComponent', ResearchImageComponent);
Vue.component('ResearchTableComponent', ResearchTableComponent);
Vue.component('uploadImageComponent', uploadImageComponent);
Vue.component('ResearchSubtitleModal', ResearchSubtitleModal);
Vue.component('InsertTableComponent', InsertTableComponent);
Vue.component('ResearchCard', ResearchCard);
Vue.component('ResearchSnackbar', ResearchSnackbar);
Vue.component('ResearchChapterCard', ResearchChapterCard);
Vue.component('ResearchOneElement', ResearchOneElement);
Vue.component('ResearchModal', ResearchModal);
Vue.component('ThesisProjectGeneratorButton', ThesisProjectGeneratorButton);
Vue.component('ResearchHover', ResearchHover);
Vue.component('easyResearchOverlay', easyResearchOverlay);
Vue.component('expResearchElement', expResearchElement);
Vue.component('researchElementCard', researchElementCard);
Vue.component('researchElementSelector', researchElementSelector);
Vue.component('richTextarea', richTextarea);
Vue.component('Highlightable', Highlightable);
